
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RANIN
 */
public class Tiket1 extends javax.swing.JFrame {

    /**
     * Creates new form Tiket1
     */
    public Tiket1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Rb_RED = new javax.swing.JRadioButton();
        Rb_YELLOW = new javax.swing.JRadioButton();
        Rb_PINK = new javax.swing.JRadioButton();
        Rb_GREEN = new javax.swing.JRadioButton();
        Rb_PURPLE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_email = new javax.swing.JTextField();
        Txt_nama = new javax.swing.JTextField();
        Cb_tanggal = new javax.swing.JComboBox<>();
        Cb_bulan = new javax.swing.JComboBox<>();
        Cb_tahun = new javax.swing.JComboBox<>();
        Txt_Harga = new javax.swing.JTextField();
        Txt_jlhPesanan = new javax.swing.JTextField();
        Txt_total = new javax.swing.JTextField();
        B_Pesan = new javax.swing.JButton();
        B_Pesanlagi = new javax.swing.JButton();
        B_Keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("TIKETKONSER.ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Pemesanan Tiket Konser EXO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 260, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Jenis Tiket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14))); // NOI18N

        buttonGroup1.add(Rb_RED);
        Rb_RED.setText("RED");
        Rb_RED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_REDActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rb_YELLOW);
        Rb_YELLOW.setText("YELLOW");
        Rb_YELLOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_YELLOWActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rb_PINK);
        Rb_PINK.setText("PINK");
        Rb_PINK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_PINKActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rb_GREEN);
        Rb_GREEN.setText("GREEN");
        Rb_GREEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_GREENActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rb_PURPLE);
        Rb_PURPLE.setText("PURPLE");
        Rb_PURPLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_PURPLEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rb_PINK, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(Rb_RED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rb_GREEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rb_YELLOW, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Rb_PURPLE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_RED)
                    .addComponent(Rb_YELLOW))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rb_PINK)
                    .addComponent(Rb_GREEN))
                .addGap(18, 18, 18)
                .addComponent(Rb_PURPLE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 190, 160));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("E-Mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Booking");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Harga Tiket");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah Pesanan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Total Bayar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 250, 30));
        jPanel1.add(Txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, 30));

        Cb_tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(Cb_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        Cb_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(Cb_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        Cb_tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPanel1.add(Cb_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        Txt_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 250, 30));

        Txt_jlhPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_jlhPesananActionPerformed(evt);
            }
        });
        Txt_jlhPesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_jlhPesananKeyReleased(evt);
            }
        });
        jPanel1.add(Txt_jlhPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 250, 30));

        Txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 250, 40));

        B_Pesan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        B_Pesan.setText("Pesan");
        B_Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PesanActionPerformed(evt);
            }
        });
        jPanel1.add(B_Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 80, 30));

        B_Pesanlagi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        B_Pesanlagi.setText("Pesan Lagi");
        B_Pesanlagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PesanlagiActionPerformed(evt);
            }
        });
        jPanel1.add(B_Pesanlagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 493, -1, 30));

        B_Keluar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        B_Keluar.setText("Keluar");
        B_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(B_Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_HargaActionPerformed

    private void Txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_totalActionPerformed

    private void Txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailActionPerformed

    private void Rb_REDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_REDActionPerformed
        Txt_Harga.setText("4800000");
        if(Rb_RED.isSelected())
        {
          Rb_YELLOW.setSelected(false);
          Rb_GREEN.setSelected(false);
          Rb_PINK.setSelected(false);
          Rb_PURPLE.setSelected(false);
        }
    }//GEN-LAST:event_Rb_REDActionPerformed

    private void Rb_YELLOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_YELLOWActionPerformed
        Txt_Harga.setText("4000000");
        if(Rb_YELLOW.isSelected())
        {
          Rb_RED.setSelected(false);
          Rb_GREEN.setSelected(false);
          Rb_PINK.setSelected(false);
          Rb_PURPLE.setSelected(false);
        }
    }//GEN-LAST:event_Rb_YELLOWActionPerformed

    private void Rb_PINKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_PINKActionPerformed
        Txt_Harga.setText("3650000");
        if(Rb_PINK.isSelected())
        {
          Rb_RED.setSelected(false);
          Rb_GREEN.setSelected(false);
          Rb_YELLOW.setSelected(false);
          Rb_PURPLE.setSelected(false);
        }
    }//GEN-LAST:event_Rb_PINKActionPerformed

    private void Rb_GREENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_GREENActionPerformed
        Txt_Harga.setText("2500000");
        if(Rb_GREEN.isSelected())
        {
          Rb_RED.setSelected(false);
          Rb_YELLOW.setSelected(false);
          Rb_PINK.setSelected(false);
          Rb_PURPLE.setSelected(false);
        }
    }//GEN-LAST:event_Rb_GREENActionPerformed

    private void Rb_PURPLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_PURPLEActionPerformed
        Txt_Harga.setText("1850000");
        if(Rb_PURPLE.isSelected())
        {
          Rb_RED.setSelected(false);
          Rb_GREEN.setSelected(false);
          Rb_PINK.setSelected(false);
          Rb_YELLOW.setSelected(false);
        }
    }//GEN-LAST:event_Rb_PURPLEActionPerformed

    private void Txt_jlhPesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_jlhPesananKeyReleased
        int Harga = Integer.valueOf(Txt_Harga.getText());
        
        String output;
        double a = Double.valueOf(Txt_jlhPesanan.getText());
        double b = Double.valueOf(Txt_Harga.getText());
        double hasil = Harga * a;
        output = String.valueOf(hasil);
        Txt_total.setText(output);
    }//GEN-LAST:event_Txt_jlhPesananKeyReleased

    private void B_PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PesanActionPerformed
        jTextArea1.setText(
                   "Nama                             : "+ Txt_nama.getText()+ "\n"+
                   "E-Mail                             : "+ Txt_email.getText()+ "\n"+
                   "Harga Tiket                    : "+ Txt_Harga.getText()+ "\n"+
                   "Jumlah Pesanan          : "+ Txt_jlhPesanan.getText()+ "\n"+
                   "Total                                : "+ Txt_total.getText()+ "\n");
       
    }//GEN-LAST:event_B_PesanActionPerformed

    private void B_PesanlagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PesanlagiActionPerformed
        buttonGroup1.clearSelection();
        Txt_Harga.setText("");
        Txt_nama.setText("");
        Txt_email.setText("");
        Cb_tanggal.setSelectedItem("Tanggal");
        Cb_bulan.setSelectedItem("Bulan");
        Cb_tahun.setSelectedItem("Tahun");
        Txt_jlhPesanan.setText("");
        Txt_total.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_B_PesanlagiActionPerformed

    private void B_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_KeluarActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this,"Anda yakin ingin keluar","Keluar", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);
        if(jawab==0){
          JOptionPane.showMessageDialog(this,"Anda akan keluar dari program ini");
          System.exit(0);
        }
    }//GEN-LAST:event_B_KeluarActionPerformed

    private void Txt_jlhPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_jlhPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_jlhPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Keluar;
    private javax.swing.JButton B_Pesan;
    private javax.swing.JButton B_Pesanlagi;
    private javax.swing.JComboBox<String> Cb_bulan;
    private javax.swing.JComboBox<String> Cb_tahun;
    private javax.swing.JComboBox<String> Cb_tanggal;
    private javax.swing.JRadioButton Rb_GREEN;
    private javax.swing.JRadioButton Rb_PINK;
    private javax.swing.JRadioButton Rb_PURPLE;
    private javax.swing.JRadioButton Rb_RED;
    private javax.swing.JRadioButton Rb_YELLOW;
    private javax.swing.JTextField Txt_Harga;
    private javax.swing.JTextField Txt_email;
    private javax.swing.JTextField Txt_jlhPesanan;
    private javax.swing.JTextField Txt_nama;
    private javax.swing.JTextField Txt_total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
